### ISSUE TITLE
Detalles a cambiar del sitio en general

### ISSUE THREAD

**Issue by Miguelslo27** [Miguelslo27/capacitacion-in-company#14]
- [x] Cambiar el title: Pestaña del navegador, que quede sólo **Capacitación in company** (respetando la mayúscula y minúsculas)
- [x] Poner FavIcon: Pestaña del navegador, imagen del logo con la C en color rojito.
- [x] Cambiar los subtítulos del Slider: Sustituir el texto **"Sistema de compras estatales …"** hasta **"Soluciones"** por **"Brindamos capacitación de calidad, personalizada, ajustada a tus necesidades y en tu lugar de trabajo."**
- [x] Borrar el texto y la línea gris que está encima de **"A continuación te presentamos cuatro buenas razones para hacer los cursos con nosotros"**

**Comment by ElTroesma** [comment]
La descripcion del sitio se une al texto. @Miguelslo27

**Comment by Miguelslo27** [comment]
Listo, dejé sólo el título
