### ISSUE TITLE
Cambiar el texto del Slider princial

### ISSUE THREAD

**Issue by Miguelslo27** [Miguelslo27/capacitacion-in-company#4]
Poner como texto la descripción al pie del folleto

[Folleto](https://drive.google.com/file/d/1kVi9hnwCH6khL--ue7eNg9KEmtd-ONoS/view?usp=sharing)

**Comment by ElTroesma** [comment]
Se agregó link al botón de "Ver cursos" que direcciona a la pestaña de cursos.
